# POST http://localhost:5001/api/student/register


## get all students
GET http://localhost:5001/api/student  

###Testing adding an institution
POST http://localhost:5001/api/admin/addInstitution
Content-Type: application/json

{
  "name": "National University of Lesotho",
  "description": "A top university in Lesotho"
}

###Testing student registration
POST http://localhost:5001/api/student/register
Content-Type: application/json

{
  "name": "Rankuatsana",
  "email": "ranks@example.com",
  "password": "hello2468"
}
###Testing company registration
POST http://localhost:5001/api/company/register
Content-Type: application/json

{
  "name": "Tech Solutions",
  "email": "tch@gmail.com",
  "password": "tech1234" 
}

###Testing institute registration
POST http://localhost:5001/api/institute/register   
Content-Type: application/json

{
  "name": "Global Tech Institute",
  "email": "gtc@gmail.com",
  "password": "global1234" 
}

###Testing admin registration
POST http://localhost:5001/api/admin/register  
Content-Type: application/json

{
  "name": "Admin User",
  "email": "ad1@gmail.com",
  "password": "admin1234"
}